config/routes.rb
Rails.application.routes.draw do
  resources :character_sheets

  devise_for :users
  root 'pages#home'

end

app/models/character_sheet.rb
class CharacterSheet < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/character_sheets_controller.rb
class CharacterSheetsController < ApplicationController
  before_action :set_character_sheet, only: [:show, :edit, :update, :destroy]

  # GET /character_sheets
  # GET /character_sheets.json
  def index
    @character_sheets = CharacterSheet.all
  end

  # GET /character_sheets/1
  # GET /character_sheets/1.json
  def show
  end

  # GET /character_sheets/new
  def new
    @character_sheet = CharacterSheet.new
  end

  # GET /character_sheets/1/edit
  def edit
  end

  # POST /character_sheets
  # POST /character_sheets.json
  def create
    @character_sheet = CharacterSheet.new(character_sheet_params)

    respond_to do |format|
      if @character_sheet.save
        format.html { redirect_to @character_sheet, notice: 'Character sheet was successfully created.' }
        format.json { render :show, status: :created, location: @character_sheet }
      else
        format.html { render :new }
        format.json { render json: @character_sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /character_sheets/1
  # PATCH/PUT /character_sheets/1.json
  def update
    respond_to do |format|
      if @character_sheet.update(character_sheet_params)
        format.html { redirect_to @character_sheet, notice: 'Character sheet was successfully updated.' }
        format.json { render :show, status: :ok, location: @character_sheet }
      else
        format.html { render :edit }
        format.json { render json: @character_sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /character_sheets/1
  # DELETE /character_sheets/1.json
  def destroy
    @character_sheet.destroy
    respond_to do |format|
      format.html { redirect_to character_sheets_url, notice: 'Character sheet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character_sheet
      @character_sheet = CharacterSheet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_sheet_params
      params.require(:character_sheet).permit(:CharacterName)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/character_sheets_helper.rb
module CharacterSheetsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/character_sheets/_form.html.erb
<%= form_for(@character_sheet) do |f| %>
  <% if @character_sheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@character_sheet.errors.count, "error") %> prohibited this character_sheet from being saved:</h2>

      <ul>
      <% @character_sheet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :CharacterName %><br>
    <%= f.text_field :CharacterName %><br>
    <%= f.label :PlayerName %><br>
    <%= f.text_field :PlayerName %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/character_sheets/edit.html.erb
<h1>Editing character_sheet</h1>

<%= render 'form' %>

<%= link_to 'Show', @character_sheet %> |
<%= link_to 'Back', character_sheets_path %>

app/views/character_sheets/index.html.erb
<h1>Listing Character Sheets</h1>

<table>
  <thead>
    <tr>
      <th>Character Name</th>
      <th>Player Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @character_sheets.each do |character_sheet| %>
      <tr>
        <td><%= character_sheet.CharacterName %></td>
        <td><%= character_sheet.PlayerName %></td>
        <td><%= link_to 'Show', character_sheet %></td>
        <td><%= link_to 'Edit', edit_character_sheet_path(character_sheet) %></td>
        <td><%= link_to 'Destroy', character_sheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Character sheet', new_character_sheet_path %>

app/views/character_sheets/new.html.erb
<h1>New character_sheet</h1>

<%= render 'form' %>

<%= link_to 'Back', character_sheets_path %>

app/views/character_sheets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Character Name:</strong>
  <%= @character_sheet.CharacterName %>
  <strong>Player Name:</strong>
  <%= @character_sheet.PlayerName %>
</p>

<%= link_to 'Edit', edit_character_sheet_path(@character_sheet) %> |
<%= link_to 'Back', character_sheets_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Pathfinder Character Sheets</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <% if user_signed_in? %>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pathfindersheets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron center">
     <h1>Welcome to my app!</h1>
     <% if user_signed_in? %>
          # do something
     <% else %>
       <p>
         <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
         <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
       </p>
  <% end %>
</div>